import { faker } from '@faker-js/faker';

/**
 * Test Data:
 * Test data files store the input values and expected outputs used across test cases. 
 * They help separate the test logic from the data, ensuring tests remain flexible and reusable.
 * By keeping data like form inputs, URLs, or expected messages in dedicated files, you can 
 * easily update and manage values without changing the test logic. This approach also allows 
 * for dynamic data generation using libraries like Faker, and ensures test cases remain clean 
 * and focused on behavior rather than hardcoded values.
 */

// Test data for tests, static hardcoded and also autogenerated by faker

export const testData = {
  
  // User credentials for login - hardcoded
  email: 'petr.brablc@gmail.com',
  password: '123456',

  // User credentials for login - generated by faker
  randomEmail: () => faker.internet.email(),
  randomPassword: () => faker.internet.password(),

  // New upload test data
  upload: {
    recordTitle: () => faker.lorem.sentence(), // Function to generate a random title
    familyName: () => faker.lorem.word(), // Function to generate a random family name
    recordDescription: () => faker.lorem.paragraph(), // Function to generate a random description
    filePath: './path/to/your/file.txt', // Path to the file to be uploaded
    successMessage: 'Upload successful', // Expected success message upon a successful upload

    // Dynamic resource type - Select randomly from a list
    resourceType: () => faker.helpers.arrayElement(['Image', 'Video', 'Dataset', 'Other', 'Audio']),
  },
};