name: Run Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  QASE_TESTOPS_PROJECT: ${{ secrets.QASE_TESTOPS_PROJECT }}
  QASE_TESTOPS_API_TOKEN: ${{ secrets.QASE_TESTOPS_API_TOKEN }}
  QASE_ENVIRONMENT: ${{ secrets.QASE_ENVIRONMENT || 'Invenio-RDM' }}
  HEADLESS: true

jobs:
  tests_e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    environment: Invenio-RDM
    timeout-minutes: 120

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run all tests (initial pass)
        run: npx playwright test || true

      - name: Verify JSON report exists
        run: |
          if [ -f test-results.json ]; then
            echo "JSON report generated"
          else
            echo "test-results.json not found - zkontroluj reporter v configu!"
            exit 1
          fi

      - name: Extract failed test files
        run: node .github/scripts/extract-failed-tests.js > failed-tests.txt
        continue-on-error: true

      - name: Retry failed tests (just once at the end)
        if: success() || failure()
        run: |
          if [ -s failed-tests.txt ]; then
            echo "Retrying failed tests:"
            cat failed-tests.txt
            xargs -a failed-tests.txt -I {} sh -c 'npx playwright test {} || true'
          else
            echo "No failed tests to retry."
          fi

      - name: Finalize Qase run
        run: node .github/scripts/globalTeardown.js

      - name: Upload Playwright HTML report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30